/**
 * GDExtension Addon Structure Build Step
 * 
 * This step creates the proper addon directory structure for a GDExtension
 * so it can be consumed by Godot projects. It organizes the .gdextension file
 * and binaries into the correct addon format.
 */

import * as fs from 'fs';
import * as path from 'path';
import { BuildStep, BuildContext } from '../core/interfaces';
import { FileSystemError } from '../core/errors';


/**
 * Options for the GDExtension addon step
 */
export interface GDExtensionAddonStepOptions {
  /** Custom addon name (defaults to project name) */
  readonly addonName?: string;
  /** Whether to create plugin.cfg file */
  readonly createPluginConfig?: boolean;
  /** Plugin description for plugin.cfg */
  readonly pluginDescription?: string;
  /** Plugin author for plugin.cfg */
  readonly pluginAuthor?: string;
  /** Plugin version for plugin.cfg */
  readonly pluginVersion?: string;
}

/**
 * Build step that creates GDExtension addon structure
 */
export class GDExtensionAddonStep implements BuildStep {
  readonly name = 'GDExtension Addon Structure';

  constructor(private readonly options: GDExtensionAddonStepOptions = {}) {}

  async execute(context: BuildContext): Promise<void> {
    try {
      const buildDir = context.buildDir;
      const addonName = this.options.addonName || context.projectName;
      
      // For GDExtensions, we create the addon structure directly in the build directory
      // so it can be properly symlinked by the dependency linking system
      
      // The .gdextension file and bin directory should already be in the build directory
      // We just need to create the plugin.cfg file
      
      // Create plugin.cfg if requested
      if (this.options.createPluginConfig !== false) {
        await this.createPluginConfig(context, buildDir, addonName);
      }

      console.log(`GDExtension addon structure created in build directory: ${buildDir}`);

    } catch (error) {
      throw new FileSystemError(
        `Failed to create GDExtension addon structure: ${error instanceof Error ? error.message : String(error)}`,
        context.projectName,
        error instanceof Error ? error : undefined
      );
    }
  }



  /**
   * Create plugin.cfg file for the addon
   */
  private async createPluginConfig(_context: BuildContext, buildDir: string, addonName: string): Promise<void> {
    const pluginConfigPath = path.join(buildDir, 'plugin.cfg');
    
    const pluginName = this.formatPluginName(addonName);
    const description = this.options.pluginDescription || `GDExtension plugin for ${pluginName}`;
    const author = this.options.pluginAuthor || 'Generated by Nx Godot Build Tools';
    const version = this.options.pluginVersion || '1.0.0';

    const pluginConfig = `[plugin]

name="${pluginName}"
description="${description}"
author="${author}"
version="${version}"
script=""
`;

    fs.writeFileSync(pluginConfigPath, pluginConfig, 'utf8');
    console.log(`Created plugin.cfg: ${pluginConfigPath}`);
  }

  /**
   * Format addon name for display in plugin.cfg
   */
  private formatPluginName(addonName: string): string {
    // Convert kebab-case to Title Case
    return addonName
      .split('-')
      .map(word => word.charAt(0).toUpperCase() + word.slice(1))
      .join(' ');
  }
}